### ISSUE TITLE
Injectable Application alternative class?

### ISSUE THREAD

**Issue by mbits** [hprange/woinject#10]
It would be appreciated if the InjectableApplication class code be placed into a separate service class, so that the developer doesn't have to extend InjectableApplication. This is because it is likely that the Application class is already extending a custom Application class.

Cheers,
Matt

**Comment by paulhoadley** [comment]
Just curious—was this ticket closed because the solution is obvious? I'm just test-driving WOInject, and I've run into the same problem—existing framework-level `Application` superclass makes it unclear where `InjectableApplication` should fit into the hierarchy. Is this solvable?
